//
// Copyright (c) ZeroC, Inc. All rights reserved.
//
//
// Ice version 3.7.2
//
// <auto-generated>
//
// Generated from file `Printer.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

#include <Printer.h>
#include <IceUtil/PushDisableWarnings.h>
#include <Ice/LocalException.h>
#include <Ice/ValueFactory.h>
#include <Ice/OutgoingAsync.h>
#include <Ice/InputStream.h>
#include <Ice/OutputStream.h>
#include <IceUtil/PopDisableWarnings.h>

#if defined(_MSC_VER)
#   pragma warning(disable:4458) // declaration of ... hides class member
#elif defined(__clang__)
#   pragma clang diagnostic ignored "-Wshadow"
#elif defined(__GNUC__)
#   pragma GCC diagnostic ignored "-Wshadow"
#endif

#ifndef ICE_IGNORE_VERSION
#   if ICE_INT_VERSION / 100 != 307
#       error Ice version mismatch!
#   endif
#   if ICE_INT_VERSION % 100 > 50
#       error Beta header file detected
#   endif
#   if ICE_INT_VERSION % 100 < 2
#       error Ice patch level mismatch!
#   endif
#endif

#ifdef ICE_CPP11_MAPPING // C++11 mapping

namespace
{

const ::std::string iceC_Demo_ServerService_ids[2] =
{
    "::Demo::ServerService",
    "::Ice::Object"
};
const ::std::string iceC_Demo_ServerService_ops[] =
{
    "ice_id",
    "ice_ids",
    "ice_isA",
    "ice_ping",
    "requireService"
};
const ::std::string iceC_Demo_ServerService_requireService_name = "requireService";

const ::std::string iceC_Demo_ClientCallback_ids[2] =
{
    "::Demo::ClientCallback",
    "::Ice::Object"
};
const ::std::string iceC_Demo_ClientCallback_ops[] =
{
    "callback",
    "ice_id",
    "ice_ids",
    "ice_isA",
    "ice_ping"
};
const ::std::string iceC_Demo_ClientCallback_callback_name = "callback";

}

bool
Demo::ServerService::ice_isA(::std::string s, const ::Ice::Current&) const
{
    return ::std::binary_search(iceC_Demo_ServerService_ids, iceC_Demo_ServerService_ids + 2, s);
}

::std::vector<::std::string>
Demo::ServerService::ice_ids(const ::Ice::Current&) const
{
    return ::std::vector<::std::string>(&iceC_Demo_ServerService_ids[0], &iceC_Demo_ServerService_ids[2]);
}

::std::string
Demo::ServerService::ice_id(const ::Ice::Current&) const
{
    return ice_staticId();
}

const ::std::string&
Demo::ServerService::ice_staticId()
{
    static const ::std::string typeId = "::Demo::ServerService";
    return typeId;
}

/// \cond INTERNAL
bool
Demo::ServerService::_iceD_requireService(::IceInternal::Incoming& inS, const ::Ice::Current& current)
{
    _iceCheckMode(::Ice::OperationMode::Normal, current.mode);
    auto istr = inS.startReadParams();
    ::std::string iceP_ident;
    ::std::string iceP_s;
    istr->readAll(iceP_ident, iceP_s);
    inS.endReadParams();
    this->requireService(::std::move(iceP_ident), ::std::move(iceP_s), current);
    inS.writeEmptyParams();
    return true;
}
/// \endcond

/// \cond INTERNAL
bool
Demo::ServerService::_iceDispatch(::IceInternal::Incoming& in, const ::Ice::Current& current)
{
    ::std::pair<const ::std::string*, const ::std::string*> r = ::std::equal_range(iceC_Demo_ServerService_ops, iceC_Demo_ServerService_ops + 5, current.operation);
    if(r.first == r.second)
    {
        throw ::Ice::OperationNotExistException(__FILE__, __LINE__, current.id, current.facet, current.operation);
    }

    switch(r.first - iceC_Demo_ServerService_ops)
    {
        case 0:
        {
            return _iceD_ice_id(in, current);
        }
        case 1:
        {
            return _iceD_ice_ids(in, current);
        }
        case 2:
        {
            return _iceD_ice_isA(in, current);
        }
        case 3:
        {
            return _iceD_ice_ping(in, current);
        }
        case 4:
        {
            return _iceD_requireService(in, current);
        }
        default:
        {
            assert(false);
            throw ::Ice::OperationNotExistException(__FILE__, __LINE__, current.id, current.facet, current.operation);
        }
    }
}
/// \endcond

bool
Demo::ClientCallback::ice_isA(::std::string s, const ::Ice::Current&) const
{
    return ::std::binary_search(iceC_Demo_ClientCallback_ids, iceC_Demo_ClientCallback_ids + 2, s);
}

::std::vector<::std::string>
Demo::ClientCallback::ice_ids(const ::Ice::Current&) const
{
    return ::std::vector<::std::string>(&iceC_Demo_ClientCallback_ids[0], &iceC_Demo_ClientCallback_ids[2]);
}

::std::string
Demo::ClientCallback::ice_id(const ::Ice::Current&) const
{
    return ice_staticId();
}

const ::std::string&
Demo::ClientCallback::ice_staticId()
{
    static const ::std::string typeId = "::Demo::ClientCallback";
    return typeId;
}

/// \cond INTERNAL
bool
Demo::ClientCallback::_iceD_callback(::IceInternal::Incoming& inS, const ::Ice::Current& current)
{
    _iceCheckMode(::Ice::OperationMode::Normal, current.mode);
    auto istr = inS.startReadParams();
    ::std::string iceP_s;
    istr->readAll(iceP_s);
    inS.endReadParams();
    this->callback(::std::move(iceP_s), current);
    inS.writeEmptyParams();
    return true;
}
/// \endcond

/// \cond INTERNAL
bool
Demo::ClientCallback::_iceDispatch(::IceInternal::Incoming& in, const ::Ice::Current& current)
{
    ::std::pair<const ::std::string*, const ::std::string*> r = ::std::equal_range(iceC_Demo_ClientCallback_ops, iceC_Demo_ClientCallback_ops + 5, current.operation);
    if(r.first == r.second)
    {
        throw ::Ice::OperationNotExistException(__FILE__, __LINE__, current.id, current.facet, current.operation);
    }

    switch(r.first - iceC_Demo_ClientCallback_ops)
    {
        case 0:
        {
            return _iceD_callback(in, current);
        }
        case 1:
        {
            return _iceD_ice_id(in, current);
        }
        case 2:
        {
            return _iceD_ice_ids(in, current);
        }
        case 3:
        {
            return _iceD_ice_isA(in, current);
        }
        case 4:
        {
            return _iceD_ice_ping(in, current);
        }
        default:
        {
            assert(false);
            throw ::Ice::OperationNotExistException(__FILE__, __LINE__, current.id, current.facet, current.operation);
        }
    }
}
/// \endcond

/// \cond INTERNAL
void
Demo::ServerServicePrx::_iceI_requireService(const ::std::shared_ptr<::IceInternal::OutgoingAsyncT<void>>& outAsync, const ::std::string& iceP_ident, const ::std::string& iceP_s, const ::Ice::Context& context)
{
    outAsync->invoke(iceC_Demo_ServerService_requireService_name, ::Ice::OperationMode::Normal, ::Ice::FormatType::DefaultFormat, context,
        [&](::Ice::OutputStream* ostr)
        {
            ostr->writeAll(iceP_ident, iceP_s);
        },
        nullptr);
}
/// \endcond

/// \cond INTERNAL
::std::shared_ptr<::Ice::ObjectPrx>
Demo::ServerServicePrx::_newInstance() const
{
    return ::IceInternal::createProxy<ServerServicePrx>();
}
/// \endcond

const ::std::string&
Demo::ServerServicePrx::ice_staticId()
{
    return ServerService::ice_staticId();
}

/// \cond INTERNAL
void
Demo::ClientCallbackPrx::_iceI_callback(const ::std::shared_ptr<::IceInternal::OutgoingAsyncT<void>>& outAsync, const ::std::string& iceP_s, const ::Ice::Context& context)
{
    outAsync->invoke(iceC_Demo_ClientCallback_callback_name, ::Ice::OperationMode::Normal, ::Ice::FormatType::DefaultFormat, context,
        [&](::Ice::OutputStream* ostr)
        {
            ostr->writeAll(iceP_s);
        },
        nullptr);
}
/// \endcond

/// \cond INTERNAL
::std::shared_ptr<::Ice::ObjectPrx>
Demo::ClientCallbackPrx::_newInstance() const
{
    return ::IceInternal::createProxy<ClientCallbackPrx>();
}
/// \endcond

const ::std::string&
Demo::ClientCallbackPrx::ice_staticId()
{
    return ClientCallback::ice_staticId();
}

#else // C++98 mapping

namespace
{

const ::std::string iceC_Demo_ServerService_requireService_name = "requireService";

const ::std::string iceC_Demo_ClientCallback_callback_name = "callback";

}

/// \cond INTERNAL
::IceProxy::Ice::Object* ::IceProxy::Demo::upCast(ServerService* p) { return p; }

void
::IceProxy::Demo::_readProxy(::Ice::InputStream* istr, ::IceInternal::ProxyHandle< ServerService>& v)
{
    ::Ice::ObjectPrx proxy;
    istr->read(proxy);
    if(!proxy)
    {
        v = 0;
    }
    else
    {
        v = new ServerService;
        v->_copyFrom(proxy);
    }
}
/// \endcond

::Ice::AsyncResultPtr
IceProxy::Demo::ServerService::_iceI_begin_requireService(const ::std::string& iceP_ident, const ::std::string& iceP_s, const ::Ice::Context& context, const ::IceInternal::CallbackBasePtr& del, const ::Ice::LocalObjectPtr& cookie, bool sync)
{
    ::IceInternal::OutgoingAsyncPtr result = new ::IceInternal::CallbackOutgoing(this, iceC_Demo_ServerService_requireService_name, del, cookie, sync);
    try
    {
        result->prepare(iceC_Demo_ServerService_requireService_name, ::Ice::Normal, context);
        ::Ice::OutputStream* ostr = result->startWriteParams(::Ice::DefaultFormat);
        ostr->write(iceP_ident);
        ostr->write(iceP_s);
        result->endWriteParams();
        result->invoke(iceC_Demo_ServerService_requireService_name);
    }
    catch(const ::Ice::Exception& ex)
    {
        result->abort(ex);
    }
    return result;
}

void
IceProxy::Demo::ServerService::end_requireService(const ::Ice::AsyncResultPtr& result)
{
    _end(result, iceC_Demo_ServerService_requireService_name);
}

/// \cond INTERNAL
::IceProxy::Ice::Object*
IceProxy::Demo::ServerService::_newInstance() const
{
    return new ServerService;
}
/// \endcond

const ::std::string&
IceProxy::Demo::ServerService::ice_staticId()
{
    return ::Demo::ServerService::ice_staticId();
}

/// \cond INTERNAL
::IceProxy::Ice::Object* ::IceProxy::Demo::upCast(ClientCallback* p) { return p; }

void
::IceProxy::Demo::_readProxy(::Ice::InputStream* istr, ::IceInternal::ProxyHandle< ClientCallback>& v)
{
    ::Ice::ObjectPrx proxy;
    istr->read(proxy);
    if(!proxy)
    {
        v = 0;
    }
    else
    {
        v = new ClientCallback;
        v->_copyFrom(proxy);
    }
}
/// \endcond

::Ice::AsyncResultPtr
IceProxy::Demo::ClientCallback::_iceI_begin_callback(const ::std::string& iceP_s, const ::Ice::Context& context, const ::IceInternal::CallbackBasePtr& del, const ::Ice::LocalObjectPtr& cookie, bool sync)
{
    ::IceInternal::OutgoingAsyncPtr result = new ::IceInternal::CallbackOutgoing(this, iceC_Demo_ClientCallback_callback_name, del, cookie, sync);
    try
    {
        result->prepare(iceC_Demo_ClientCallback_callback_name, ::Ice::Normal, context);
        ::Ice::OutputStream* ostr = result->startWriteParams(::Ice::DefaultFormat);
        ostr->write(iceP_s);
        result->endWriteParams();
        result->invoke(iceC_Demo_ClientCallback_callback_name);
    }
    catch(const ::Ice::Exception& ex)
    {
        result->abort(ex);
    }
    return result;
}

void
IceProxy::Demo::ClientCallback::end_callback(const ::Ice::AsyncResultPtr& result)
{
    _end(result, iceC_Demo_ClientCallback_callback_name);
}

/// \cond INTERNAL
::IceProxy::Ice::Object*
IceProxy::Demo::ClientCallback::_newInstance() const
{
    return new ClientCallback;
}
/// \endcond

const ::std::string&
IceProxy::Demo::ClientCallback::ice_staticId()
{
    return ::Demo::ClientCallback::ice_staticId();
}

Demo::ServerService::~ServerService()
{
}

/// \cond INTERNAL
::Ice::Object* Demo::upCast(ServerService* p) { return p; }

/// \endcond

namespace
{
const ::std::string iceC_Demo_ServerService_ids[2] =
{
    "::Demo::ServerService",
    "::Ice::Object"
};

}

bool
Demo::ServerService::ice_isA(const ::std::string& s, const ::Ice::Current&) const
{
    return ::std::binary_search(iceC_Demo_ServerService_ids, iceC_Demo_ServerService_ids + 2, s);
}

::std::vector< ::std::string>
Demo::ServerService::ice_ids(const ::Ice::Current&) const
{
    return ::std::vector< ::std::string>(&iceC_Demo_ServerService_ids[0], &iceC_Demo_ServerService_ids[2]);
}

const ::std::string&
Demo::ServerService::ice_id(const ::Ice::Current&) const
{
    return ice_staticId();
}

const ::std::string&
Demo::ServerService::ice_staticId()
{
#ifdef ICE_HAS_THREAD_SAFE_LOCAL_STATIC
    static const ::std::string typeId = "::Demo::ServerService";
    return typeId;
#else
    return iceC_Demo_ServerService_ids[0];
#endif
}

/// \cond INTERNAL
bool
Demo::ServerService::_iceD_requireService(::IceInternal::Incoming& inS, const ::Ice::Current& current)
{
    _iceCheckMode(::Ice::Normal, current.mode);
    ::Ice::InputStream* istr = inS.startReadParams();
    ::std::string iceP_ident;
    ::std::string iceP_s;
    istr->read(iceP_ident);
    istr->read(iceP_s);
    inS.endReadParams();
    this->requireService(iceP_ident, iceP_s, current);
    inS.writeEmptyParams();
    return true;
}
/// \endcond

namespace
{
const ::std::string iceC_Demo_ServerService_all[] =
{
    "ice_id",
    "ice_ids",
    "ice_isA",
    "ice_ping",
    "requireService"
};

}

/// \cond INTERNAL
bool
Demo::ServerService::_iceDispatch(::IceInternal::Incoming& in, const ::Ice::Current& current)
{
    ::std::pair<const ::std::string*, const ::std::string*> r = ::std::equal_range(iceC_Demo_ServerService_all, iceC_Demo_ServerService_all + 5, current.operation);
    if(r.first == r.second)
    {
        throw ::Ice::OperationNotExistException(__FILE__, __LINE__, current.id, current.facet, current.operation);
    }

    switch(r.first - iceC_Demo_ServerService_all)
    {
        case 0:
        {
            return _iceD_ice_id(in, current);
        }
        case 1:
        {
            return _iceD_ice_ids(in, current);
        }
        case 2:
        {
            return _iceD_ice_isA(in, current);
        }
        case 3:
        {
            return _iceD_ice_ping(in, current);
        }
        case 4:
        {
            return _iceD_requireService(in, current);
        }
        default:
        {
            assert(false);
            throw ::Ice::OperationNotExistException(__FILE__, __LINE__, current.id, current.facet, current.operation);
        }
    }
}
/// \endcond

/// \cond STREAM
void
Demo::ServerService::_iceWriteImpl(::Ice::OutputStream* ostr) const
{
    ostr->startSlice(ice_staticId(), -1, true);
    ::Ice::StreamWriter< ServerService, ::Ice::OutputStream>::write(ostr, *this);
    ostr->endSlice();
}

void
Demo::ServerService::_iceReadImpl(::Ice::InputStream* istr)
{
    istr->startSlice();
    ::Ice::StreamReader< ServerService, ::Ice::InputStream>::read(istr, *this);
    istr->endSlice();
}
/// \endcond

/// \cond INTERNAL
void
Demo::_icePatchObjectPtr(ServerServicePtr& handle, const ::Ice::ObjectPtr& v)
{
    handle = ServerServicePtr::dynamicCast(v);
    if(v && !handle)
    {
        IceInternal::Ex::throwUOE(ServerService::ice_staticId(), v);
    }
}
/// \endcond

Demo::ClientCallback::~ClientCallback()
{
}

/// \cond INTERNAL
::Ice::Object* Demo::upCast(ClientCallback* p) { return p; }

/// \endcond

namespace
{
const ::std::string iceC_Demo_ClientCallback_ids[2] =
{
    "::Demo::ClientCallback",
    "::Ice::Object"
};

}

bool
Demo::ClientCallback::ice_isA(const ::std::string& s, const ::Ice::Current&) const
{
    return ::std::binary_search(iceC_Demo_ClientCallback_ids, iceC_Demo_ClientCallback_ids + 2, s);
}

::std::vector< ::std::string>
Demo::ClientCallback::ice_ids(const ::Ice::Current&) const
{
    return ::std::vector< ::std::string>(&iceC_Demo_ClientCallback_ids[0], &iceC_Demo_ClientCallback_ids[2]);
}

const ::std::string&
Demo::ClientCallback::ice_id(const ::Ice::Current&) const
{
    return ice_staticId();
}

const ::std::string&
Demo::ClientCallback::ice_staticId()
{
#ifdef ICE_HAS_THREAD_SAFE_LOCAL_STATIC
    static const ::std::string typeId = "::Demo::ClientCallback";
    return typeId;
#else
    return iceC_Demo_ClientCallback_ids[0];
#endif
}

/// \cond INTERNAL
bool
Demo::ClientCallback::_iceD_callback(::IceInternal::Incoming& inS, const ::Ice::Current& current)
{
    _iceCheckMode(::Ice::Normal, current.mode);
    ::Ice::InputStream* istr = inS.startReadParams();
    ::std::string iceP_s;
    istr->read(iceP_s);
    inS.endReadParams();
    this->callback(iceP_s, current);
    inS.writeEmptyParams();
    return true;
}
/// \endcond

namespace
{
const ::std::string iceC_Demo_ClientCallback_all[] =
{
    "callback",
    "ice_id",
    "ice_ids",
    "ice_isA",
    "ice_ping"
};

}

/// \cond INTERNAL
bool
Demo::ClientCallback::_iceDispatch(::IceInternal::Incoming& in, const ::Ice::Current& current)
{
    ::std::pair<const ::std::string*, const ::std::string*> r = ::std::equal_range(iceC_Demo_ClientCallback_all, iceC_Demo_ClientCallback_all + 5, current.operation);
    if(r.first == r.second)
    {
        throw ::Ice::OperationNotExistException(__FILE__, __LINE__, current.id, current.facet, current.operation);
    }

    switch(r.first - iceC_Demo_ClientCallback_all)
    {
        case 0:
        {
            return _iceD_callback(in, current);
        }
        case 1:
        {
            return _iceD_ice_id(in, current);
        }
        case 2:
        {
            return _iceD_ice_ids(in, current);
        }
        case 3:
        {
            return _iceD_ice_isA(in, current);
        }
        case 4:
        {
            return _iceD_ice_ping(in, current);
        }
        default:
        {
            assert(false);
            throw ::Ice::OperationNotExistException(__FILE__, __LINE__, current.id, current.facet, current.operation);
        }
    }
}
/// \endcond

/// \cond STREAM
void
Demo::ClientCallback::_iceWriteImpl(::Ice::OutputStream* ostr) const
{
    ostr->startSlice(ice_staticId(), -1, true);
    ::Ice::StreamWriter< ClientCallback, ::Ice::OutputStream>::write(ostr, *this);
    ostr->endSlice();
}

void
Demo::ClientCallback::_iceReadImpl(::Ice::InputStream* istr)
{
    istr->startSlice();
    ::Ice::StreamReader< ClientCallback, ::Ice::InputStream>::read(istr, *this);
    istr->endSlice();
}
/// \endcond

/// \cond INTERNAL
void
Demo::_icePatchObjectPtr(ClientCallbackPtr& handle, const ::Ice::ObjectPtr& v)
{
    handle = ClientCallbackPtr::dynamicCast(v);
    if(v && !handle)
    {
        IceInternal::Ex::throwUOE(ClientCallback::ice_staticId(), v);
    }
}
/// \endcond

namespace Ice
{
}

#endif
